# Generated by Django 5.0.6 on 2024-06-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basic_sa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin_number', models.CharField(max_length=100)),
                ('min_basic_sa', models.FloatField(blank=True, null=True)),
                ('max_basic_sa', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='case_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin_number', models.CharField(max_length=100)),
                ('case_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin_number', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='entry_age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin_number', models.CharField(max_length=100)),
                ('min_entry_age', models.IntegerField(blank=True, null=True)),
                ('max_entry_age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='functionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin_number', models.CharField(max_length=100)),
                ('functionality', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin_number', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='maturity_age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin_number', models.CharField(max_length=100)),
                ('min_maturity_age', models.IntegerField(blank=True, null=True)),
                ('max_maturity_age', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='modes_of_premiums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin_number', models.CharField(max_length=100)),
                ('modes_of_premiums', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mudrank_stamp_duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin_number', models.CharField(max_length=100)),
                ('mudrank_stamp_duty', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='payer_third_party_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin_number', models.CharField(max_length=100)),
                ('payer_third_party_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='policy_term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin_number', models.CharField(max_length=100)),
                ('min_policy_term', models.IntegerField(blank=True, null=True)),
                ('max_policy_term', models.IntegerField(blank=True, null=True)),
                ('specific_ppt', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin_number', models.CharField(max_length=100)),
                ('min_premium', models.FloatField(blank=True, null=True)),
                ('max_premium', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='proposal_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin_number', models.CharField(max_length=100)),
                ('proposal_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='smoker_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin_number', models.CharField(max_length=100)),
                ('smoker_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='standard_age_proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin_number', models.CharField(max_length=100)),
                ('standard_age_proof', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
