# Generated by Django 5.0.6 on 2024-06-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datageneratorapp', '0002_allscenario_delete_basic_sa_delete_case_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allscenario',
            name='entry_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
