# Generated by Django 5.0.6 on 2024-06-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datageneratorapp', '0003_allscenario_entry_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allscenario',
            name='entry_age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
