# Generated by Django 5.0.6 on 2024-06-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datageneratorapp', '0004_alter_allscenario_entry_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allscenario',
            name='entry_age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
