# Generated by Django 5.0.6 on 2024-06-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datageneratorapp', '0006_rename_specific_ppt_allscenario_basic_sa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allscenario',
            name='max_ppt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allscenario',
            name='min_ppt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allscenario',
            name='ppt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
